export type BusinessTypeId = 'jdg'|'sp-zoo'|'sa'|'sp-j'|'sp-k'|'ska'|'sp-p'|'ngo'|'spoldzielnia'|'holding';

export interface UseCase {
  id: string;
  titlePl: string;
  titleEn: string;
  descPl: string;
  descEn: string;
  bt: BusinessTypeId[];
}

export interface UseCaseCategory {
  id: string;
  color: string;
  titlePl: string;
  titleEn: string;
  cases: UseCase[];
}

export const BT_META: Record<BusinessTypeId, { shortPl: string; shortEn: string; fullPl: string }> = {
  jdg:          { shortPl: 'JDG',           shortEn: 'Sole Trader',      fullPl: 'Jednoosobowa działalność gospodarcza' },
  'sp-zoo':     { shortPl: 'Sp. z o.o.',    shortEn: 'Ltd.',             fullPl: 'Spółka z ograniczoną odpowiedzialnością' },
  sa:           { shortPl: 'S.A.',           shortEn: 'JSC',              fullPl: 'Spółka Akcyjna' },
  'sp-j':       { shortPl: 'Sp. j.',         shortEn: 'Gen. Partnership', fullPl: 'Spółka Jawna' },
  'sp-k':       { shortPl: 'Sp. k.',         shortEn: 'Ltd. Partnership', fullPl: 'Spółka Komandytowa' },
  ska:          { shortPl: 'S.K.A.',         shortEn: 'LJSP',             fullPl: 'Spółka Komandytowo-Akcyjna' },
  'sp-p':       { shortPl: 'Sp. p.',         shortEn: 'Prof. Partnership',fullPl: 'Spółka Partnerska' },
  ngo:          { shortPl: 'NGO / Fundacja', shortEn: 'NGO / Foundation', fullPl: 'Fundacja, Stowarzyszenie, OPP' },
  spoldzielnia: { shortPl: 'Spółdzielnia',   shortEn: 'Co-operative',     fullPl: 'Spółdzielnia pracy / mieszkaniowa' },
  holding:      { shortPl: 'Holding / Grupa',shortEn: 'Holding / Group',  fullPl: 'Wielospółkowa grupa kapitałowa' },
};

export const BT_ALL: BusinessTypeId[] = ['jdg','sp-zoo','sa','sp-j','sp-k','ska','sp-p','ngo','spoldzielnia','holding'];

const A: BusinessTypeId[] = BT_ALL;
const C: BusinessTypeId[] = ['sp-zoo','sa','sp-j','sp-k','ska','sp-p','spoldzielnia','holding'];
const CORP: BusinessTypeId[] = ['sp-zoo','sa','sp-k','ska','holding'];
const H: BusinessTypeId[] = ['holding'];

export const USE_CASE_DATA: UseCaseCategory[] = [
  {
    id: 'hr', color: 'emerald',
    titlePl: 'HR, Kadry i Płace', titleEn: 'HR, Payroll & People',
    cases: [
      { id: 'hr-01', titlePl: 'Onboarding nowego pracownika z automatyczną checklistą', titleEn: 'New employee onboarding with automated checklist', descPl: 'Automatyczna checklista przydziela zadania HR, IT i kierownikowi. Podpisanie umowy przez e-podpis pierwszego dnia.', descEn: 'Automated checklist assigns tasks to HR, IT and manager. Contract signed via e-signature on day one.', bt: C },
      { id: 'hr-02', titlePl: 'Naliczanie listy płac z ZUS i podatkiem dochodowym', titleEn: 'Payroll calculation with ZUS and income tax', descPl: 'Automatyczne naliczanie wynagrodzeń brutto/netto, składek ZUS, zaliczki PIT. Generowanie DRA i pasków płacowych PDF.', descEn: 'Automatic gross/net salary calculation, ZUS contributions, PIT advance. DRA and payslip PDF generation.', bt: C },
      { id: 'hr-03', titlePl: 'Elektroniczne wnioski urlopowe i ewidencja czasu pracy', titleEn: 'Electronic leave requests and time attendance tracking', descPl: 'Pracownicy składają wnioski urlopowe online, kierownik zatwierdza jednym kliknięciem. Czas pracy ewidencjonowany automatycznie.', descEn: 'Employees submit leave requests online; manager approves with one click. Work time recorded automatically.', bt: A },
      { id: 'hr-04', titlePl: 'Elektroniczna teczka pracownicza zgodna z RODO', titleEn: 'Digital employee folder — GDPR compliant', descPl: 'Pełna e-teczka pracownika z automatyczną retencją danych — dokumenty usuwane po upłynięciu okresu przechowywania zgodnie z RODO.', descEn: 'Full digital employee folder with GDPR-compliant retention — documents auto-deleted after retention period.', bt: C },
      { id: 'hr-05', titlePl: 'Dynamiczny org-chart — struktura organizacyjna online', titleEn: 'Dynamic org chart — live organisational structure', descPl: 'Org-chart generowany automatycznie z danych HR, widoczny dla pracowników, aktualizowany w czasie rzeczywistym.', descEn: 'Org chart auto-generated from HR data, visible to employees, updated in real time.', bt: C },
      { id: 'hr-06', titlePl: 'System rekrutacji ATS z portalem kariery (iFrame embed)', titleEn: 'ATS recruitment system with careers portal (iFrame embed)', descPl: 'Kanban rekrutacyjny z etapami: aplikacja, screening, rozmowa, oferta. Portal kariery jako widget na stronie WWW firmy.', descEn: 'Recruitment Kanban with stages: application, screening, interview, offer. Careers portal as website widget.', bt: C },
      { id: 'hr-07', titlePl: 'Oceny pracownicze 360° — AI generuje 60 kompetencji w 2 min', titleEn: '360° performance reviews — AI generates 60 competencies in 2 min', descPl: 'Cykliczne oceny z feedbackiem od przełożonego, współpracowników i podwładnych. AI Coach generuje profil kompetencji w 2 minuty.', descEn: 'Periodic 360° reviews with feedback from manager, peers and reports. AI Coach generates competency profile in 2 minutes.', bt: C },
      { id: 'hr-08', titlePl: 'Platforma szkoleniowa LMS z certyfikatami', titleEn: 'LMS training platform with certificates', descPl: 'E-learning z kursami, quizami i certyfikatami. Rejestr szkoleń BHP, uprawnień i terminów ważności badań lekarskich.', descEn: 'E-learning with courses, quizzes and certificates. Safety training, qualifications and medical check expiry registry.', bt: C },
      { id: 'hr-09', titlePl: 'Offboarding pracownika z automatyczną checklistą odejścia', titleEn: 'Employee offboarding with automated exit checklist', descPl: 'Automatyczne zadania przy odejściu: zwrot sprzętu, cofnięcie dostępów, wysyłka świadectwa pracy. Zgodność z RODO.', descEn: 'Automatic offboarding tasks: equipment return, access revocation, document dispatch. GDPR compliant.', bt: C },
      { id: 'hr-10', titlePl: 'Delegacje i podróże służbowe — rozliczanie kosztów', titleEn: 'Business travel and expense reporting', descPl: 'Wnioski delegacyjne, rozliczanie diet, biletów i noclegów. Automatyczne przeliczanie walut przy delegacjach zagranicznych.', descEn: 'Travel requests, per-diem, ticket and hotel settlement. Automatic currency conversion for international trips.', bt: A },
      { id: 'hr-11', titlePl: 'Grafik pracy i planowanie zmian dla pracowników zmianowych', titleEn: 'Work schedule and shift planning', descPl: 'Grafik pracy z widokiem tygodniowym i miesięcznym dla pracowników zmianowych. Automatyczne naliczanie nadgodzin.', descEn: 'Work schedule with weekly and monthly views for shift workers. Automatic overtime calculation.', bt: C },
      { id: 'hr-12', titlePl: 'Samoobsługowy portal HR w języku polskim i angielskim', titleEn: 'Self-service HR portal in Polish and English', descPl: 'Portal pracowniczy dwujęzyczny — wnioski, paski płacowe, dokumenty, dane kontaktowe. Dostępny z telefonu.', descEn: 'Bilingual employee portal — requests, payslips, documents, contact data. Mobile accessible.', bt: C },
      { id: 'hr-13', titlePl: 'Ankiety satysfakcji i wellbeing pracowników', titleEn: 'Employee satisfaction and wellbeing surveys', descPl: 'Cykliczne ankiety eNPS i badania dobrostanu. Dashboard wellness z wykresami trendów dla działu HR.', descEn: 'Periodic eNPS surveys and wellbeing assessments. Wellness dashboard with trend charts for HR.', bt: C },
      { id: 'hr-14', titlePl: 'Ewidencja badań lekarskich i szkoleń BHP z alertami', titleEn: 'Medical examinations and safety training with alerts', descPl: 'Automatyczne alerty o kończących się badaniach lekarskich, szkoleniach BHP i uprawnieniach. Rejestr zgodny z Kodeksem Pracy.', descEn: 'Automatic alerts for expiring medical exams, safety training and qualifications. Labour Code compliant.', bt: C },
      { id: 'hr-15', titlePl: 'Integracja z ZUS e-Płatnik — automatyczne deklaracje', titleEn: 'ZUS e-Płatnik integration — automatic declarations', descPl: 'Automatyczne generowanie deklaracji ZUS DRA i RCA. Eksport do e-Płatnika. Alerty o zbliżających się terminach.', descEn: 'Automatic ZUS DRA/RCA declarations and export to e-Płatnik. Upcoming deadline alerts.', bt: C },
      { id: 'hr-16', titlePl: 'Zarządzanie benefitami pracowniczymi — pakiety medyczne, karty sportowe', titleEn: 'Employee benefits management — medical packages, gym cards', descPl: 'Ewidencja benefitów pracowniczych. Pracownik widzi przyznane benefity w portalu. Kontrola kosztów dla HR.', descEn: 'Employee benefits registry. Employee sees assigned benefits in portal. Cost control for HR.', bt: CORP },
      { id: 'hr-17', titlePl: 'Raporty kadrowe — zatrudnienie, fluktuacja, koszty pracy', titleEn: 'HR analytics — headcount, turnover, labour costs', descPl: 'Automatyczne raporty zarządcze: stan zatrudnienia, fluktuacja kadr, koszty pracy, absencja. Wykresy interaktywne.', descEn: 'Automated management reports: headcount, staff turnover, labour costs, absence. Interactive charts.', bt: C },
      { id: 'hr-18', titlePl: 'Zarządzanie umowami B2B i kontraktami freelancerów', titleEn: 'B2B contracts and freelancer management', descPl: 'Rejestr umów B2B z alertami o wygasaniu. E-podpis umów, historia zmian, archiwum DMS.', descEn: 'B2B contract registry with expiry alerts. E-signed contracts, change history, DMS archive.', bt: A },
    ],
  },
  {
    id: 'finance', color: 'blue',
    titlePl: 'Finanse, Fakturowanie i Kontroling', titleEn: 'Finance, Invoicing & Controlling',
    cases: [
      { id: 'fin-01', titlePl: 'Faktury VAT i KSeF — Krajowy System e-Faktur', titleEn: 'VAT invoicing and KSeF — National e-Invoice System', descPl: 'Wystawiaj faktury VAT i wysyłaj bezpośrednio do KSeF MF bez dodatkowych aplikacji. Automatyczne numerowanie i archiwizacja.', descEn: 'Issue VAT invoices and send directly to the National e-Invoice System (KSeF) — no additional software needed.', bt: A },
      { id: 'fin-02', titlePl: 'Generowanie JPK_V7M, JPK_V7K, JPK_FA i JPK_CIT', titleEn: 'JPK/SAF-T generation — V7M, V7K, FA, CIT', descPl: 'Automatyczne generowanie wszystkich plików JPK jednym kliknięciem — VAT (V7M/V7K), Faktur (FA) i CIT dla US.', descEn: 'One-click generation of all JPK/SAF-T files: VAT (V7M/V7K), Invoices (FA) and CIT for the tax office.', bt: A },
      { id: 'fin-03', titlePl: 'Faktury kosztowe — OCR AI i automatyczny booking w FK', titleEn: 'Purchase invoice OCR and auto-booking in GL', descPl: 'AI skanuje faktury kosztowe z e-maila i PDF — rozpoznaje NIP, kwoty, MPK i automatycznie bookuje w systemie. 80% redukcja czasu.', descEn: 'AI scans purchase invoices from email and PDF — recognises VAT number, amounts, cost centre and auto-books. 80% time reduction.', bt: A },
      { id: 'fin-04', titlePl: 'Faktury cykliczne i abonamentowe — automatyczne wystawianie', titleEn: 'Recurring and subscription invoices — automatic issuance', descPl: 'Automatyczne wystawianie faktur cyklicznych (miesięczne, kwartalne). Alerty przy błędach i braku płatności.', descEn: 'Automatic recurring invoices (monthly, quarterly). Alerts on errors and missed payments.', bt: A },
      { id: 'fin-05', titlePl: 'Import wyciągów bankowych MT940 — AI matching transakcji', titleEn: 'Bank statement import MT940 — AI transaction matching', descPl: 'Import wyciągów MT940/CSV. AI automatycznie paruje przelewy z fakturami — 90% transakcji dopasowanych bez ingerencji.', descEn: 'MT940/CSV statement import. AI automatically matches transfers to invoices — 90% matched without human input.', bt: A },
      { id: 'fin-06', titlePl: 'PSD2 Open Banking — automatyczny import transakcji z banku', titleEn: 'PSD2 Open Banking — automatic daily bank transaction import', descPl: 'Połączenie z rachunkiem bankowym przez API PSD2. Transakcje importowane codziennie automatycznie bez ręcznego pobierania wyciągów.', descEn: 'Bank account connection via PSD2 API. Transactions imported daily automatically — no manual statement download.', bt: A },
      { id: 'fin-07', titlePl: 'Środki trwałe — ewidencja, amortyzacja i przeglądy', titleEn: 'Fixed assets — registry, depreciation, maintenance schedules', descPl: 'Ewidencja środków trwałych z automatycznym naliczaniem amortyzacji (liniowa, degresywna). Alerty przeglądów i ubezpieczeń.', descEn: 'Fixed assets registry with automatic depreciation (linear, degressive). Maintenance and insurance alerts.', bt: C },
      { id: 'fin-08', titlePl: 'Budżetowanie roczne z centrami kosztów MPK', titleEn: 'Annual budgeting with cost centres (MPK)', descPl: 'Tworzenie budżetów per centrum kosztów MPK. Import struktury z Comarch/Symfonia. Analiza wykonania vs plan w czasie rzeczywistym.', descEn: 'Budgets per cost centre. Import from Comarch/Symfonia. Real-time actual vs plan analysis.', bt: CORP },
      { id: 'fin-09', titlePl: 'Controlling — analiza odchyleń budżetowych przez AI Coach', titleEn: 'Controlling — AI Coach budget variance analysis', descPl: 'AI analizuje odchylenia budżetowe, identyfikuje anomalie kosztowe i generuje raport wyjaśnień dla zarządu automatycznie.', descEn: 'AI analyses budget variances, identifies cost anomalies and auto-generates explanation reports for management.', bt: CORP },
      { id: 'fin-10', titlePl: 'Konsolidacja finansowa grupy spółek — automatyczna', titleEn: 'Automatic financial consolidation of group entities', descPl: 'Automatyczna konsolidacja bilansów i P&L grupy z eliminacją transakcji wewnętrznych. Raport konsolidacyjny w czasie rzeczywistym.', descEn: 'Automatic group balance sheet and P&L consolidation with intra-group eliminations. Real-time consolidated report.', bt: H },
      { id: 'fin-11', titlePl: 'Rozliczenia inter-company między spółkami grupy', titleEn: 'Inter-company settlement between group entities', descPl: 'Automatyczne wystawianie not obciążeniowych i rozliczanie transakcji wzajemnych między spółkami. Eliminacja ręcznych uzgodnień.', descEn: 'Automatic charge notes and settlement of intra-group transactions. Eliminates manual reconciliations.', bt: H },
      { id: 'fin-12', titlePl: 'AI Guardian — wykrywanie anomalii i fraudu w fakturach', titleEn: 'AI Guardian — fraud and anomaly detection in invoices', descPl: 'Edge AI analizuje faktury przed zatwierdzeniem — wykrywa duplikaty, zawyżone kwoty, nowych dostawców. Auto-Blur danych wrażliwych (RODO).', descEn: 'Edge AI analyses invoices before approval — detects duplicates, inflated amounts, new vendors. GDPR Auto-Blur of sensitive data.', bt: A },
      { id: 'fin-13', titlePl: 'Swipe & Match — parowanie faktur z transakcjami jak karty Tinder', titleEn: 'Swipe & Match — card-swipe invoice reconciliation UI', descPl: 'Intuicyjny interfejs kart: przesuń w prawo (match z wyciągiem), w lewo (odrzuć). Redukcja czasu rozliczeń o 70%.', descEn: 'Card-swipe interface: swipe right (match with bank), left (reject). 70% reconciliation time reduction.', bt: A },
      { id: 'fin-14', titlePl: 'Out-of-Pocket — rozliczanie wydatków pracowniczych z parymu', titleEn: 'Out-of-Pocket — employee expense claims with photo receipts', descPl: 'Pracownik fotografuje paragon, AI rozpoznaje kwotę i kategorię. Wniosek trafia do akceptacji, rozliczenie przelewem.', descEn: 'Employee photographs receipt, AI recognises amount and category. Request goes to approval, settled by bank transfer.', bt: A },
      { id: 'fin-15', titlePl: 'KSeF Offline24 — backup faktur w Azure WORM Storage', titleEn: 'KSeF Offline24 — Azure WORM immutable invoice backup', descPl: 'Automatyczny backup faktur KSeF do Azure Blob (WORM — niezmienialny). Dostęp do faktur nawet przy awarii systemu MF przez 24h.', descEn: 'Automatic KSeF invoice backup to Azure Blob Storage (WORM — immutable). Invoice access even during MF system outages for 24h.', bt: A },
      { id: 'fin-16', titlePl: 'Split Invoice — podział faktury na centra kosztów MPK', titleEn: 'Split Invoice — cost centre allocation per invoice line', descPl: 'Faktura kosztowa rozdzielana procentowo lub kwotowo na wiele MPK. Import struktury MPK z Comarch ERP i Symfonia.', descEn: 'Purchase invoice split by percentage or amount across multiple cost centres. Import from Comarch ERP and Symfonia.', bt: CORP },
      { id: 'fin-17', titlePl: 'Voice Notes — dyktowanie faktur i notatek głosem (Whisper AI)', titleEn: 'Voice Notes — voice invoice and note dictation (Whisper AI)', descPl: 'Whisper AI transkrybuje dyktowane faktury i notatki kosztowe. Tryb Edge (offline) i chmura. Zgodność z ZDR.', descEn: 'Whisper AI transcribes dictated invoices and expense notes. Edge (offline) and cloud modes. ZDR compliant.', bt: A },
      { id: 'fin-18', titlePl: 'Legal Vault — archiwum uchwał i dokumentów korporacyjnych (Art. 210 KSH)', titleEn: 'Legal Vault — corporate documents archive (Art. 210 KSH)', descPl: 'Archiwum uchwał zarządu i RN z AI strażnikiem Art. 210 KSH. Temporal.io workflow zatwierdzania. 95% dokładność AI.', descEn: 'Board/supervisory board resolution archive with AI guardian (Art. 210 KSH). Temporal.io approval workflow. 95% AI accuracy.', bt: CORP },
      { id: 'fin-19', titlePl: 'Biuro rachunkowe — panel wielu klientów jako izolowanych tenantów', titleEn: 'Accounting firm — multi-client isolated tenant panel', descPl: 'Jedna platforma dla biura rachunkowego. Każdy klient jako izolowany tenant. Centralny panel statusów dokumentów.', descEn: 'One platform for an accounting firm. Each client as an isolated tenant. Central document status panel.', bt: ['sp-zoo','sa','sp-j','sp-k','sp-p'] },
      { id: 'fin-20', titlePl: 'Rozrachunki z kontrahentami — wiekowanie należności i monity', titleEn: 'Receivables ageing and automated payment reminders', descPl: 'Automatyczne wiekowanie należności z podświetleniem przeterminowanych. Wysyłka monitów płatniczych jednym kliknięciem.', descEn: 'Automatic receivables ageing with overdue highlighting. Payment reminders sent with one click.', bt: A },
      { id: 'fin-21', titlePl: 'Prognoza cash flow — AI na 30/60/90 dni', titleEn: 'AI cash flow forecast — 30/60/90 day horizon', descPl: 'AI analizuje terminowość płatności kontrahentów i generuje prognozę przepływów gotówkowych na 30, 60 i 90 dni.', descEn: 'AI analyses customer payment patterns and generates cash flow forecast for 30, 60 and 90 days.', bt: A },
      { id: 'fin-22', titlePl: 'Ewidencja kasy gotówkowej — KP/KW i raport kasowy', titleEn: 'Cash register management — receipt/payment vouchers and cash report', descPl: 'Ewidencja operacji kasowych: kwitki KP i KW. Dzienny raport kasowy z uzgodnieniem salda.', descEn: 'Cash transaction recording: KP receipt and KW payment vouchers. Daily cash report with balance reconciliation.', bt: A },
    ],
  },
  {
    id: 'crm', color: 'violet',
    titlePl: 'CRM, Sprzedaż i Obsługa Klienta', titleEn: 'CRM, Sales & Customer Service',
    cases: [
      { id: 'crm-01', titlePl: 'Baza klientów 360° z pełną historią interakcji', titleEn: '360° customer database with full interaction history', descPl: 'Kompletny widok klienta: kontakty, oferty, faktury, maile, spotkania i notatki. Import danych z GUS (NIP) i VIES.', descEn: 'Complete client view: contacts, quotes, invoices, emails, meetings and notes. Data import from GUS (VAT) and VIES.', bt: A },
      { id: 'crm-02', titlePl: 'Zarządzanie lejkiem sprzedaży — Kanban i pipeline AI', titleEn: 'Sales pipeline management — Kanban with AI insights', descPl: 'Kanban sprzedażowy z etapami pipeline, wartością szans i prognozą. AI Coach sugeruje następne akcje i priorytety.', descEn: 'Sales Kanban with pipeline stages, opportunity values and forecast. AI Coach suggests next actions and priorities.', bt: A },
      { id: 'crm-03', titlePl: 'Oferty handlowe — konwersja na fakturę jednym kliknięciem', titleEn: 'Sales quotes — one-click conversion to invoice', descPl: 'Profesjonalne oferty z cenami, rabatami i warunkami. Jeden przycisk konwertuje ofertę na fakturę lub zamówienie.', descEn: 'Professional quotes with prices, discounts and terms. One button converts quote to invoice or purchase order.', bt: A },
      { id: 'crm-04', titlePl: 'E-podpis umów sprzedażowych — klient podpisuje przez link', titleEn: 'Sales contract e-signature — client signs via link', descPl: 'Umowy wysyłane klientowi przez link — podpisuje elektronicznie bez instalacji aplikacji. Podpis zaawansowany i kwalifikowany.', descEn: 'Contracts sent to client via link — they sign electronically without any app install. Advanced and qualified e-signatures.', bt: A },
      { id: 'crm-05', titlePl: 'Portal klienta — faktury, umowy i zamówienia przez bezpieczny link', titleEn: 'Customer portal — invoices, contracts and orders via secure link', descPl: 'Klient loguje się do portalu przez token. Pobiera faktury, podpisuje umowy, śledzi zamówienia. Bez konta w systemie.', descEn: 'Client logs into portal via token. Downloads invoices, signs contracts, tracks orders. No account in the system needed.', bt: A },
      { id: 'crm-06', titlePl: 'Booking online — widget rezerwacji na stronie WWW (iFrame)', titleEn: 'Online booking — website widget embed (iFrame)', descPl: 'Widget rezerwacji na stronie WWW firmy (iFrame embed). Klient wybiera termin, usługę i pracownika. Automatyczne potwierdzenie mailem.', descEn: 'Booking widget embedded on company website (iFrame). Client selects date, service and staff. Automatic email confirmation.', bt: A },
      { id: 'crm-07', titlePl: 'Leads to Cash — od leada do faktury w jednym systemie', titleEn: 'Leads to Cash — from lead to invoice in one system', descPl: 'Lead → kwalifikacja → oferta → umowa → realizacja → faktura → płatność — bez przepisywania danych między systemami.', descEn: 'Lead → qualification → quote → contract → delivery → invoice → payment — no re-entry between systems.', bt: A },
      { id: 'crm-08', titlePl: 'Automatyczne follow-upy i przypomnienia sprzedażowe', titleEn: 'Automated sales follow-ups and reminders', descPl: 'System wysyła reminder do handlowca po X dniach bez kontaktu. Alerty o ofertach bez odpowiedzi. Rejestr interakcji.', descEn: 'System sends reminder to salesperson after X days without contact. Alerts on unanswered quotes. Interaction log.', bt: A },
      { id: 'crm-09', titlePl: 'Import kontrahentów z GUS — automatyczna weryfikacja NIP i VIES', titleEn: 'Contractor import from GUS — automatic VAT/VIES verification', descPl: 'Wpisz NIP — system automatycznie pobiera dane z GUS (REGON) i weryfikuje VAT w VIES UE. Zero ręcznego przepisywania.', descEn: 'Enter VAT number — system fetches data from GUS (REGON) and verifies EU VAT in VIES. Zero manual entry.', bt: A },
      { id: 'crm-10', titlePl: 'Zarządzanie reklamacjami i obsługa posprzedażowa', titleEn: 'Complaint management and after-sales support', descPl: 'Rejestr reklamacji ze śledzeniem statusu, terminami ustawowymi i automatycznymi powiadomieniami klienta.', descEn: 'Complaint registry with status tracking, statutory deadlines and automatic customer notifications.', bt: A },
      { id: 'crm-11', titlePl: 'Cenniki, rabaty i indywidualne warunki handlowe per klient', titleEn: 'Price lists, discounts and individual terms per client', descPl: 'Wiele cenników: standardowy, B2B, dla stałych klientów, sezonowy. Indywidualne rabaty per klient lub segment.', descEn: 'Multiple price lists: standard, B2B, loyal customers, seasonal. Individual discounts per client or segment.', bt: A },
      { id: 'crm-12', titlePl: 'Prognoza sprzedaży AI i analiza rentowności klienta', titleEn: 'AI sales forecast and customer profitability analysis', descPl: 'AI analizuje historię zamówień i prognozuje sprzedaż na kolejne kwartały. Automatyczna analiza marży per klient.', descEn: 'AI analyses order history and forecasts sales for upcoming quarters. Automatic margin analysis per client.', bt: CORP },
      { id: 'crm-13', titlePl: 'Kampanie marketingowe e-mail z segmentacją klientów', titleEn: 'Email marketing campaigns with customer segmentation', descPl: 'Segmentacja klientów wg branży, wartości, lokalizacji. Kampanie e-mailowe ze śledzeniem otwarć i kliknięć.', descEn: 'Customer segmentation by industry, value, location. Email campaigns with open and click tracking.', bt: A },
    ],
  },
  {
    id: 'projects', color: 'cyan',
    titlePl: 'Projekty, Zadania i Czas Pracy', titleEn: 'Projects, Tasks & Time Tracking',
    cases: [
      { id: 'proj-01', titlePl: 'Zarządzanie projektami — Kanban, Scrum i sprinty', titleEn: 'Project management — Kanban, Scrum and sprints', descPl: 'Tablice Kanban i sprinty Scrum. Backlog, story points, velocity — wszystko w jednym systemie ERP.', descEn: 'Kanban boards and Scrum sprints. Backlog, story points, velocity — all in one ERP system.', bt: A },
      { id: 'proj-02', titlePl: 'Wykresy Gantt z zależnościami i ścieżką krytyczną', titleEn: 'Gantt charts with task dependencies and critical path', descPl: 'Interaktywne wykresy Gantt z zależnościami zadań, ścieżką krytyczną i śledzeniem postępu. Alerty o opóźnieniach.', descEn: 'Interactive Gantt charts with task dependencies, critical path and progress tracking. Delay alerts.', bt: C },
      { id: 'proj-03', titlePl: 'Rejestracja czasu pracy na projekty — timesheet', titleEn: 'Project time tracking — digital timesheets', descPl: 'Rejestracja czasu na projekty i zadania. Automatyczne raporty utilization. Podstawa do fakturowania T&M.', descEn: 'Time logging on projects and tasks. Automatic utilisation reports. Basis for T&M billing.', bt: A },
      { id: 'proj-04', titlePl: 'Fakturowanie T&M — czas pracy zamieniany na fakturę', titleEn: 'T&M billing — tracked time converted to client invoice', descPl: 'Zarejestrowany czas pracy konwertowany na fakturę jednym kliknięciem. Raport szczegółowy jako załącznik do faktury.', descEn: 'Tracked time converted to client invoice with one click. Detailed report as invoice attachment.', bt: A },
      { id: 'proj-05', titlePl: 'Budżet projektowy — plan vs wykonanie w czasie rzeczywistym', titleEn: 'Project budget tracking — plan vs actual in real time', descPl: 'Śledzenie budżetu projektowego na bieżąco. Alert gdy przekroczono 80% budżetu. Analiza rentowności projektu.', descEn: 'Real-time project budget tracking. Alert when 80% of budget exceeded. Project profitability analysis.', bt: A },
      { id: 'proj-06', titlePl: 'AI dobór zespołu projektowego wg kompetencji i dostępności', titleEn: 'AI-based project team selection by skills and availability', descPl: 'AI analizuje dostępność i kompetencje pracowników, sugeruje optymalny skład zespołu z uzasadnieniem.', descEn: 'AI analyses staff availability and skills, suggesting optimal team composition with rationale.', bt: C },
      { id: 'proj-07', titlePl: 'Portfolio projektów — dashboard dla zarządu', titleEn: 'Project portfolio dashboard for management', descPl: 'Widok wszystkich projektów: status, rentowność, ryzyko, zasoby. Drill-down do szczegółów każdego projektu.', descEn: 'View of all projects: status, profitability, risk, resources. Drill-down to each project detail.', bt: CORP },
      { id: 'proj-08', titlePl: 'Szablony projektów dla branży IT, budowlanej i usługowej', titleEn: 'Project templates for IT, construction and services', descPl: 'Gotowe szablony: "Projekt IT", "Projekt budowlany", "Audyt". Nowy projekt uruchamiany w 30 sekund.', descEn: 'Ready templates: "IT Project", "Construction Project", "Audit". New project launched in 30 seconds.', bt: A },
    ],
  },
  {
    id: 'compliance', color: 'emerald',
    titlePl: 'Compliance, RODO, ESG i Jakość', titleEn: 'Compliance, GDPR, ESG & Quality',
    cases: [
      { id: 'comp-01', titlePl: 'Rejestr czynności przetwarzania danych — RODO Art. 30', titleEn: 'GDPR Article 30 processing activities register', descPl: 'Kompletny rejestr czynności przetwarzania wymagany przez RODO. Automatyczne raporty dla IOD i UODO.', descEn: 'Complete GDPR Article 30 processing activities register. Automatic reports for DPO and supervisory authority.', bt: A },
      { id: 'comp-02', titlePl: 'Platforma sygnalisty — anonimowe zgłoszenia naruszeń (EU 2019/1937)', titleEn: 'Whistleblower platform — anonymous reporting (EU Directive 2019/1937)', descPl: 'Platforma zgodna z dyrektywą EU 2019/1937. Anonimowość zgłaszającego zagwarantowana kryptograficznie.', descEn: 'EU Directive 2019/1937 compliant platform. Reporter anonymity cryptographically guaranteed.', bt: C },
      { id: 'comp-03', titlePl: 'Raportowanie ESG i CSRD — dyrektywa EU 2022/2464', titleEn: 'ESG and CSRD reporting — EU Directive 2022/2464', descPl: 'Zbieranie danych ESG z modułów systemu. Raporty zgodne z CSRD (EU 2022/2464) i GRI automatycznie.', descEn: 'ESG data collection from system modules. Automatic CSRD (EU 2022/2464) and GRI compliant reports.', bt: CORP },
      { id: 'comp-04', titlePl: 'DPIA — ocena skutków przetwarzania dla ochrony danych', titleEn: 'DPIA — data protection impact assessment workflow', descPl: 'Guided DPIA workflow z szablonem. Ocena ryzyka, opis przetwarzania, konsultacja z IOD. Archiwum DPIA.', descEn: 'Guided DPIA workflow with template. Risk assessment, processing description, DPO consultation. DPIA archive.', bt: C },
      { id: 'comp-05', titlePl: 'Obsługa żądań podmiotów danych RODO Art. 15–22 z trackerem', titleEn: 'GDPR data subject requests handling — Art. 15–22 with tracker', descPl: 'Rejestr żądań (dostęp, usunięcie, sprostowanie). Automatyczny tracker 30-dniowych terminów RODO.', descEn: 'Requests registry (access, erasure, rectification). Automatic 30-day GDPR deadline tracker.', bt: A },
      { id: 'comp-06', titlePl: 'Audyt wewnętrzny — plan roczny, program i protokoły', titleEn: 'Internal audit — annual plan, programme and protocols', descPl: 'Plan audytów, programy, listy kontrolne, protokoły. Śledzenie realizacji zaleceń pokontrolnych.', descEn: 'Audit plans, programmes, checklists, protocols. Tracking of post-audit recommendation implementation.', bt: CORP },
      { id: 'comp-07', titlePl: 'NIS2 — zarządzanie bezpieczeństwem IT i incydentami', titleEn: 'NIS2 — IT security and incident management', descPl: 'Rejestr incydentów bezpieczeństwa z czasami reakcji zgodnymi z NIS2. Zarządzanie ryzykiem IT.', descEn: 'Security incident registry with NIS2-compliant response times. IT risk management and remediation planning.', bt: CORP },
      { id: 'comp-08', titlePl: 'ISO 27001 — system zarządzania bezpieczeństwem informacji', titleEn: 'ISO 27001 — information security management system', descPl: 'Polityki bezpieczeństwa, listy kontrolne ISO 27001, ryzyka i działania korygujące. Gotowość na audit certyfikacyjny.', descEn: 'Security policies, ISO 27001 checklists, risks and corrective actions. Certification audit readiness.', bt: CORP },
      { id: 'comp-09', titlePl: 'BCM — plan ciągłości działania i zarządzanie ryzykiem operacyjnym', titleEn: 'BCM — business continuity and operational risk management', descPl: 'Ryzyka operacyjne z macierzą prawdopodobieństwo/wpływ. Plan BCP z procedurami awaryjnymi i kontaktami.', descEn: 'Operational risks with probability/impact matrix. BCP with emergency procedures and contacts.', bt: CORP },
      { id: 'comp-10', titlePl: 'Polityki i procedury wewnętrzne z potwierdzeniami elektronicznymi', titleEn: 'Internal policies and procedures with electronic acknowledgements', descPl: 'Repozytorium polityk z wersjonowaniem. Pracownicy potwierdzają zapoznanie elektronicznie. Historia wersji.', descEn: 'Policy repository with versioning. Employees confirm reading electronically. Version history.', bt: C },
      { id: 'comp-11', titlePl: 'ISO 9001 — niezgodności, CAPA i wskaźniki jakości', titleEn: 'ISO 9001 — nonconformities, CAPA and quality KPIs', descPl: 'Rejestr niezgodności i działań korygujących CAPA. Audyty jakości, certyfikaty dostawców. KPI jakości dla zarządu.', descEn: 'Nonconformities and CAPA registry. Quality audits, supplier certificates. Quality KPIs for management.', bt: CORP },
      { id: 'comp-12', titlePl: 'KYC/AML — weryfikacja kontrahentów w rejestrach i listach sankcji', titleEn: 'KYC/AML — contractor verification in registries and sanctions lists', descPl: 'Weryfikacja kontrahentów w KRS, CEIDG i listach sankcji UE/OFAC. Dokumentacja due diligence w aktach.', descEn: 'Contractor verification in KRS, CEIDG and EU/OFAC sanctions lists. Due diligence documentation in file.', bt: CORP },
    ],
  },
  {
    id: 'fieldservice', color: 'teal',
    titlePl: 'Serwis Terenowy, Logistyka i Rezerwacje', titleEn: 'Field Service, Logistics & Bookings',
    cases: [
      { id: 'fs-01', titlePl: 'Zlecenia serwisowe z GPS i mobilna aplikacja dla technika', titleEn: 'GPS-tracked service orders with technician mobile app', descPl: 'Zlecenia serwisowe, przydzielanie techników z GPS, śledzenie statusu. Mobilna aplikacja do raportowania z terenu.', descEn: 'Service orders, GPS-tracked technician assignment, real-time status. Mobile app for field reporting.', bt: A },
      { id: 'fs-02', titlePl: 'Portal klienta — samodzielna zmiana terminu wizyty serwisowej', titleEn: 'Client portal — self-service appointment rescheduling', descPl: 'Klient otrzymuje link i samodzielnie przesuwa termin wizyty bez angażowania recepcji. Token-based, bez logowania.', descEn: 'Client gets a link and reschedules visit without involving reception. Token-based, no login required.', bt: A },
      { id: 'fs-03', titlePl: 'Historia serwisowa urządzeń, gwarancje i przeglądy cykliczne', titleEn: 'Device service history, warranties and periodic maintenance', descPl: 'Pełna historia serwisowa urządzeń: przeglądy, naprawy, wymienione części, gwarancje z alertami.', descEn: 'Full device service history: maintenance, repairs, replaced parts, warranties with expiry alerts.', bt: A },
      { id: 'fs-04', titlePl: 'Zarządzanie flotą pojazdów — przeglądy i ubezpieczenia', titleEn: 'Fleet vehicle management — maintenance and insurance tracking', descPl: 'Ewidencja pojazdów z alertami o przeglądach, ubezpieczeniach i tachografach. Koszty eksploatacji i przebieg.', descEn: 'Vehicle registry with maintenance, insurance and tachograph alerts. Operating costs and mileage tracking.', bt: C },
      { id: 'fs-05', titlePl: 'Rezerwacje online 24/7 — embed na stronie WWW', titleEn: 'Online bookings 24/7 — website embed', descPl: 'System rezerwacji dostępny całą dobę przez stronę WWW. Automatyczne potwierdzenia SMS i e-mail.', descEn: '24/7 booking system via website. Automatic SMS and email confirmations. Availability management.', bt: A },
      { id: 'fs-06', titlePl: 'SLA — monitoring umów serwisowych i alertów naruszenia', titleEn: 'SLA — service level monitoring and breach alerts', descPl: 'Monitoring SLA per klient: czas reakcji, czas naprawy. Alerty o naruszeniach SLA. Raport miesięczny.', descEn: 'SLA monitoring per client: response time, repair time. Breach alerts. Monthly performance report.', bt: C },
      { id: 'fs-07', titlePl: 'Budownictwo — kosztorysy KNR i protokoły odbioru z e-podpisem', titleEn: 'Construction — KNR estimates and acceptance protocols with e-sign', descPl: 'Kosztorysy budowlane z pozycjami KNR. Protokoły odbioru z e-podpisem kierownika budowy i inwestora.', descEn: 'Construction estimates with KNR items. Acceptance protocols with e-signatures from site manager and investor.', bt: A },
      { id: 'fs-08', titlePl: 'Ogrodnictwo — sezonowe harmonogramy obsługi klientów', titleEn: 'Gardening — seasonal client maintenance schedules', descPl: 'Sezonowe harmonogramy usług ogrodniczych dla klientów stałych. Zlecenia tygodniowe, raporty z wizyt i zdjęcia.', descEn: 'Seasonal maintenance schedules for regular clients. Weekly work orders, visit reports and field photos.', bt: A },
      { id: 'fs-09', titlePl: 'Sprzątanie — harmonogramy obiektów komercyjnych i check-listy', titleEn: 'Cleaning services — commercial property schedules and checklists', descPl: 'Harmonogramy sprzątania dla obiektów. Check-listy czystości wypełniane mobilnie przez sprzątacza na miejscu.', descEn: 'Cleaning schedules for commercial properties. Cleanliness checklists filled by cleaner on-site via mobile.', bt: A },
      { id: 'fs-10', titlePl: 'Mechanika pojazdów — historia napraw i zlecenia z SMS do klienta', titleEn: 'Automotive repair — vehicle history and repair orders with SMS', descPl: 'Kartoteka pojazdu z historią napraw. Zlecenia z estymacją kosztów i akceptacją klienta przez SMS.', descEn: 'Vehicle card with repair history. Work orders with cost estimate and client approval via SMS.', bt: A },
    ],
  },
  {
    id: 'documents', color: 'orange',
    titlePl: 'Dokumenty, DMS, Workflow i E-podpis', titleEn: 'Documents, DMS, Workflow & E-signature',
    cases: [
      { id: 'doc-01', titlePl: 'Obieg dokumentów — wielopoziomowe ścieżki akceptacji', titleEn: 'Document workflow — multi-level approval paths', descPl: 'Definiowanie ścieżek akceptacji dla faktur, umów i wniosków. Równoległa lub sekwencyjna akceptacja.', descEn: 'Define approval paths for invoices, contracts and requests. Parallel or sequential approval modes.', bt: A },
      { id: 'doc-02', titlePl: 'E-podpis kwalifikowany i zaawansowany — ważny w całej UE', titleEn: 'Qualified and advanced e-signature — valid across the EU', descPl: 'Podpisuj umowy i protokoły elektronicznie. Podpis kwalifikowany równoważny notarialnemu w całej Unii Europejskiej.', descEn: 'Sign contracts and protocols electronically. Qualified e-signature legally equivalent to notarised across the EU.', bt: A },
      { id: 'doc-03', titlePl: 'DMS — archiwum dokumentów z OCR i pełnotekstowym wyszukiwaniem', titleEn: 'DMS — document archive with OCR and full-text search', descPl: 'Cyfrowe archiwum dokumentów firmy. Wyszukiwanie po treści (OCR), tagach, dacie, kategorii. Dostęp per rola.', descEn: 'Digital company document archive. Full-text search (OCR), tags, date, category. Role-based access.', bt: A },
      { id: 'doc-04', titlePl: 'Szablony dokumentów z autouzupełnianiem — umowy, oferty, protokoły', titleEn: 'Document templates with autofill — contracts, quotes, protocols', descPl: 'Szablony z autouzupełnianiem danych klienta, kontrahenta i firmy. Zero ręcznego przepisywania danych.', descEn: 'Templates with auto-filled client, contractor and company data. Zero manual data re-entry.', bt: A },
      { id: 'doc-05', titlePl: 'Wersjonowanie dokumentów i historia zmian z przywracaniem', titleEn: 'Document versioning and change history with restore', descPl: 'Każda zmiana dokumentu jako nowa wersja z autorem i datą. Przywrócenie poprzedniej wersji jednym kliknięciem.', descEn: 'Every document change saved as a new version with author and date. Restore previous version with one click.', bt: C },
      { id: 'doc-06', titlePl: 'OCR AI — automatyczne rozpoznawanie i indeksowanie faktur PDF', titleEn: 'OCR AI — automatic invoice PDF recognition and indexing', descPl: 'AI OCR skanuje faktury PDF i zdjęcia — rozpoznaje NIP, kwoty, daty i auto-przypisuje do kontrahenta.', descEn: 'AI OCR scans PDF and photo invoices — recognises VAT number, amounts, dates and auto-assigns to contractor.', bt: A },
      { id: 'doc-07', titlePl: 'Workflow Out-of-Pocket — zatwierdzanie wydatków pracowniczych', titleEn: 'Out-of-Pocket workflow — employee expense approval flow', descPl: 'Pracownik dodaje paragon → wniosek do przełożonego → zatwierdzenie → przelew na konto. Cały obieg w systemie.', descEn: 'Employee adds receipt → request to manager → approval → bank transfer. Entire workflow in the system.', bt: A },
    ],
  },
  {
    id: 'ai', color: 'rose',
    titlePl: 'AI Coach, Asystent i Automatyzacja', titleEn: 'AI Coach, Assistant & Automation',
    cases: [
      { id: 'ai-01', titlePl: 'AI Coach tryb automatyczny — raportuje i pracuje za Ciebie', titleEn: 'AI Coach automated mode — reports and works for you', descPl: 'AI Coach automatycznie generuje raporty, wypełnia formularze i wykonuje powtarzalne zadania bez udziału użytkownika.', descEn: 'AI Coach auto-generates reports, fills forms and performs repetitive tasks without user involvement.', bt: A },
      { id: 'ai-02', titlePl: 'AI Asystent — pytania i odpowiedzi o dane firmy w czasie rzeczywistym', titleEn: 'AI Assistant — real-time Q&A on your company data', descPl: 'Zapytaj: "Jaki jest stan kasy?", "Które faktury są przeterminowane?". Odpowiedzi z danych firmy na żywo.', descEn: 'Ask: "What is the cash balance?", "Which invoices are overdue?". Answers from live company data.', bt: A },
      { id: 'ai-03', titlePl: 'Automatyczne miesięczne raporty zarządcze wysyłane e-mailem', titleEn: 'Automated monthly management reports sent by email', descPl: 'Każdego 1. dnia miesiąca AI generuje raport z kluczowymi wskaźnikami, trendami i alertami dla zarządu.', descEn: 'On the 1st of each month AI generates a report with key metrics, trends and management alerts.', bt: A },
      { id: 'ai-04', titlePl: 'Wykrywanie anomalii kosztowych i podejrzanych transakcji', titleEn: 'Cost anomaly and suspicious transaction detection', descPl: 'AI monitoruje transakcje i flaguje anomalie: niezwykłe kwoty, nowi dostawcy, duplikaty faktur, nocne operacje.', descEn: 'AI monitors transactions and flags anomalies: unusual amounts, new vendors, duplicate invoices, late-night operations.', bt: A },
      { id: 'ai-05', titlePl: 'Voice Notes — dyktowanie poleceń systemowi głosem (Whisper AI Edge)', titleEn: 'Voice Notes — voice system commands (Whisper AI Edge)', descPl: 'Dyktuj polecenia i notatki głosem. Whisper AI działa offline w trybie Edge — dane nie opuszczają sieci firmy.', descEn: 'Dictate commands and notes by voice. Whisper AI runs offline in Edge mode — data never leaves the company network.', bt: A },
      { id: 'ai-06', titlePl: 'AI screening kandydatów — ranking aplikacji i dopasowanie do profilu', titleEn: 'AI candidate screening — application ranking and profile matching', descPl: 'AI analizuje CVs, ocenia dopasowanie do stanowiska i rankinguje aplikacje. Redukcja czasu screeningu o 60%.', descEn: 'AI analyses CVs, evaluates profile fit and ranks applications. 60% reduction in screening time.', bt: C },
      { id: 'ai-07', titlePl: 'Predykcja cash flow AI — prognoza 30/60/90 dni z 85% dokładnością', titleEn: 'AI cash flow prediction — 30/60/90 day forecast at 85% accuracy', descPl: 'AI analizuje dane historyczne i prognozuje przepływy gotówkowe z 85% dokładnością. Alert przy ryzyku niedoboru.', descEn: 'AI analyses historical data and forecasts cash flows at 85% accuracy. Alert when shortage risk detected.', bt: A },
    ],
  },
  {
    id: 'multi', color: 'indigo',
    titlePl: 'Multi-Firma, Holding i Biuro Rachunkowe', titleEn: 'Multi-Entity, Holding & Accounting Firms',
    cases: [
      { id: 'multi-01', titlePl: 'Zarządzanie wieloma spółkami z jednego panelu — jedno logowanie', titleEn: 'Manage multiple entities from one panel — single sign-on', descPl: 'Przełączanie między spółkami grupy jednym kliknięciem. Izolowane dane, wspólna nawigacja i SSO.', descEn: 'Switch between group entities with one click. Isolated data, shared navigation and SSO.', bt: H },
      { id: 'multi-02', titlePl: 'Automatyczna konsolidacja bilansów grupy spółek', titleEn: 'Automatic group balance sheet and P&L consolidation', descPl: 'Konsolidacja bilansów i rachunków wyników z eliminacją transakcji wzajemnych. Dashboard grupy w czasie rzeczywistym.', descEn: 'Balance sheet and P&L consolidation with intra-group eliminations. Real-time group dashboard.', bt: H },
      { id: 'multi-03', titlePl: 'Cross-company role — użytkownik z różnymi rolami w spółkach grupy', titleEn: 'Cross-company roles — user with different roles across entities', descPl: 'Jeden użytkownik z różnymi rolami w spółkach grupy. Doradca zewnętrzny widzi tylko swoje spółki-klientów.', descEn: 'One user with different roles across group entities. External advisor sees only their client entities.', bt: H },
      { id: 'multi-04', titlePl: 'Global Dashboard CQRS — centralny widok grupy dla zarządu', titleEn: 'Global Dashboard CQRS — central group view for management', descPl: 'Dashboard zarządu: przychody, marże, cash flow, zatrudnienie — wszystkie spółki w jednym widoku. Architektura CQRS.', descEn: 'Management dashboard: revenue, margins, cash flow, headcount — all entities in one view. CQRS architecture.', bt: H },
      { id: 'multi-05', titlePl: 'Biuro rachunkowe — obsługa dziesiątek klientów z jednej platformy', titleEn: 'Accounting firm — serving dozens of clients from one platform', descPl: 'Każdy klient biura jako izolowany tenant. Centralny panel statusów dokumentów, deadlinów podatkowych i zadań.', descEn: 'Each accounting client as an isolated tenant. Central panel for document status, tax deadlines and tasks.', bt: ['sp-zoo','sa','sp-j','sp-k','sp-p'] },
      { id: 'multi-06', titlePl: 'Segment reporting — wyniki finansowe per segment biznesowy', titleEn: 'Segment reporting — financial results per business segment', descPl: 'Podział wyników na segmenty ("Polska", "Niemcy", "Usługi IT"). Raport konsolidacyjny per segment dla RN.', descEn: 'Results split into segments ("Poland", "Germany", "IT Services"). Consolidated report per segment for board.', bt: H },
    ],
  },
];
